# ICT-LIBRARY-OFFICE/monitoring/grafana.ini

# =========================================================
# SECURITY
# =========================================================
[security]

# ADMIN LOGIN
admin_user = admin
admin_password = 5785498

# ✅ ALLOW GRAFANA INSIDE IFRAME
allow_embedding = true


# =========================================================
# AUTHENTICATION
# =========================================================
[auth]

# KEEP LOGIN FORM
disable_login_form = false


# =========================================================
# ANONYMOUS VIEWER ACCESS
# =========================================================
[auth.anonymous]

# ✅ REQUIRED FOR FRONTEND EMBED
enabled = true

# VIEW ONLY
org_role = Viewer


# =========================================================
# USER SETTINGS
# =========================================================
[users]

# DISABLE PUBLIC SIGNUP
allow_sign_up = false


# =========================================================
# PATHS
# =========================================================
[paths]

data = /var/lib/grafana


# =========================================================
# SERVER
# =========================================================
[server]

http_port = 3000