// frontend/src/utils/courseAcronyms.ts

export const COURSE_ACRONYMS: Record<string, string> = {

  "BACHELOR OF SCIENCE IN SOCIAL WORK": "BSSW",

  "BACHELOR OF SCIENCE IN PSYCHOLOGY": "BS PSYCH",

  "BACHELOR OF ARTS IN SOCIOLOGY": "AB-SOCIO",

  "BACHELOR OF SCIENCE IN BIOLOGY": "BSBIO",

  "BACHELOR OF SCIENCE IN CHEMISTRY": "BSCHEM",

  "BACHELOR OF SCIENCE IN PHYSICS": "BS-PHYS",

  "BACHELOR OF SCIENCE IN MATHEMATICS": "BSMATH",

  "BACHELOR OF SCIENCE IN APPLIED MATHEMATICS": "BSAM",

  "BACHELOR OF SCIENCE IN COMPUTER SCIENCE": "BSCS",

  "BACHELOR OF SCIENCE IN INFORMATION SYSTEM": "BSIS",

  "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY": "BSIT",

  "BACHELOR OF SCIENCE IN ENVIRONMENTAL SCIENCE": "BSES",

  "BACHELOR OF SCIENCE IN AGROFORESTRY": "BSAF",

  "BACHELOR OF SCIENCE IN FORESTRY": "BSF",

  "BACHELOR OF ELEMENTARY EDUCATION": "BEED",

  "BACHELOR OF SECONDARY EDUCATION MAJOR IN ENGLISH": "BSED ENG",

  "BACHELOR OF SECONDARY EDUCATION MAJOR IN FILIPINO": "BSED FIL",

  "BACHELOR OF SECONDARY EDUCATION MAJOR IN SCIENCE": "BSED SCI",

  "BACHELOR OF SECONDARY EDUCATION MAJOR IN MATHEMATICS": "BSED-MATH",

  "BACHELOR OF AGRICULTURAL TECHNOLOGY": "BAT",

  "BACHELOR OF SCIENCE IN AGRICULTURE": "BSA",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN AGRICULTURAL ECONOMICS": "BSA-AGECON",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN AGRONOMY": "BSA-AGRON",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN CROP PROTECTION": "BSA-CROPPROT",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN SOIL SCIENCE": "BSA-SOILSCI",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN AGRIBUSINESS MANAGEMENT": "BSA-ABM",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN ANIMAL SCIENCE": "BSA-ANSCI",

  "BACHELOR OF SCIENCE IN AGRICULTURE, MAJOR IN HORTICULTURE": "BSA-HORTI",

  "BACHELOR OF SCIENCE IN AGRICULTURAL AND BIOSYSTEMS ENGINEERING": "BSABE",

  "BACHELOR OF SCIENCE IN CIVIL ENGINEERING": "BSCE",

  "BACHELOR OF SCIENCE IN ELECTRONICS ENGINEERING": "BSEcE",

  "BACHELOR OF SCIENCE IN GEODETIC ENGINEERING": "BSGE",

  "BACHELOR OF SCIENCE IN MINING ENGINEERING": "BSEM",

  "BACHELOR OF SCIENCE IN GEOLOGY": "BSGeo",

  "MASTER OF ARTS IN EDUCATION (MAED)": "MAED",

  "MAED - ENGLISH LANGUAGE TEACHING (ELT)": "MAED-ELT",

  "MAED - EDUCATIONAL MANAGEMENT (EM)": "MAED-EM",

  "MAED - GUIDANCE & COUNSELING (GC)": "MAED-GC",

  "MAED - TEACHING, READING AND LITERATURE (TRL)": "MAED-TRL",

  "MAED - HEALTH EDUCATION (HE)": "MAED-HE",

  "MASTER OF ARTS IN GUIDANCE AND COUNSELING (MA GC)": "MAGC",

  "MASTER OF SCIENCE IN ENVIRONMENTAL MANAGEMENT (MEM)": "MEM",

  "MASTER OF SCIENCE IN BIOLOGY (MSBio)": "MS Biology",

  "MSBio - MORPHOLOGY": "MSBio MORPH",

  "MSBio - ECOLOGY": "MSBio ECO",

  "MSBio - TAXONOMY": "MSBio TAX",

  "MSBio - GENETICS": "MSBio GEN",

  "MSBio - PHYSIOLOGY": "MSBio PHYS",

  "MASTER OF SCIENCE EDUCATION (MSciED)": "MSciED",

  "MSciED - BIOLOGICAL SCIENCES": "MSciEd-BIO",

  "MSciED - PHYSICAL SCIENCES": "MSciEd-PHYS",

  "MSciED - ELEMENTARY SCIENCES": "MSciEd-ELEM",

  "MASTER OF SCIENCE IN CROP SCIENCE (MSCS)": "MSCS",

  "MSCS - HORTICULTURE": "MSCS-HORT",

  "MSCS - AGRONOMY": "MSCS-AGRON",

  "MASTER OF SCIENCE IN INFORMATION TECHNOLOGY (MSIT)": "MSIT",

  "MASTER OF SCIENCE IN MATHEMATICS (MSMATH)": "MSMATH",

  "MASTER OF SCIENCE IN MATHEMATICS EDUCATION (MSMathEd)": "MSMathEd",

  "MASTER IN PUBLIC ADMINISTRATION (MPA)": "MPA",

  "DOCTOR OF EDUCATION IN EDUCATIONAL MANAGEMENT (Ed.D)": "Ed.D",

  "DOCTOR OF PHILOSOPHY IN MATHEMATICS (Ph.D.-Math)": "PHD-MATH",

  "DOCTOR OF PHILOSOPHY IN MATHEMATICS EDUCATION (Ph.D.-MathEd)": "PHD-MATHED",

  "DOCTOR OF PHILOSOPHY IN SCIENCE EDUCATION (Ph.D.-SciEd)": "PHD-SCIED",

  "Ph.D.-SciEd (Biology)": "PHD SCIED BIO",

  "Ph.D.-SciEd (Physics)": "PHD SCIED PHYS",

};